### ISSUE TITLE
Public folder generated after yarn build not working

### ISSUE THREAD

**Issue by Piero87** [ReactJSResources/react-webpack-babel#302]
Hi,
I have tried the yarn build command, but when I go to public folder and open the index.html file on Chrome, I see nothing, in the console there are no error,  if I use yarn start or yarn dev I can see the content of the page. someone can explain me why?

thanks

**Comment by Yhozen** [comment]
I got the same problem

**Comment by Piero87** [comment]
If it's useful, this is the public generated:

[public.zip](https://github.com/ReactJSResources/react-webpack-babel/files/1581859/public.zip)

**Comment by alicoding** [comment]
Hi @Piero87 and @Yhozen 

So, this is kind of an expected behavior with React Router similar to this issue https://github.com/ReactTraining/react-router/issues/3567 where you need to setup a webserver in order to get it working 

You can if you are using Mac/Linux simply run the following command inside `public` directory:

```
python -m SimpleHTTPServer 8000
```
Then it should work for you :)

**Comment by alicoding** [comment]
We've just updated the readme to include some instruction in case people run into similar issue here.

**Comment by Piero87** [comment]
Thanks!
